name: system_settings_2
description: Flutter plugin to open system and app settings on iOS and Android.
version: 3.0.0
homepage: https://github.com/timmaffett/system_settings_2
repository: https://github.com/timmaffett/system_settings_2
issue_tracker: https://github.com/timmaffett/system_settings_2/issues
screenshots:
  - description: 'android system settings'
    path: media/example.png
  - description: 'app system settings'
    path: media/app_settings.png

topics:
  - native
  - system
  - app
  - settings

environment:
  sdk: '>=2.15.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.hiveright.system_settings_2
        pluginClass: SystemSettingsPlugin
      ios:
        pluginClass: SystemSettingsPlugin
